# Generated by Django 4.2.6 on 2023-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negr_app', '0004_alter_products_created_at_alter_products_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
