# Generated by Django 4.2.6 on 2023-10-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negr_app', '0006_rename_songs_albums_rename_singers_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=6)),
                ('date_of_birth', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.country')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.instruments')),
            ],
        ),
    ]
