# Generated by Django 4.2.6 on 2023-11-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negr_app', '0007_instruments_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.directors')),
            ],
        ),
    ]
