# Generated by Django 4.2.6 on 2023-11-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Negr_app', '0008_directors_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='poster',
        ),
    ]
