# Generated by Django 4.2.6 on 2023-11-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negr_app', '0014_project_task_remove_albums_singer_delete_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('date_of_publication', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('student_card_number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Negr_app.student_group')),
            ],
        ),
        migrations.CreateModel(
            name='Process_of_taking_a_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.access_card')),
                ('title_of_the_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.literature')),
            ],
        ),
        migrations.AddField(
            model_name='access_card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negr_app.student'),
        ),
    ]
